### ISSUE TITLE
Wrong UTF-8 flag after escaping

### ISSUE THREAD

**Issue by AnotherOneAckap** [yanick/Escape-Houdini#7]
Hello and thank you for your module!
Hope you have a few spare time to consider my case.

There is warning in houdini readme:
Houdini parses only UTF-8 strings, and generates only UTF-8 strings. If you are using another encoding, you should probably transcode before passing the buffer to Houdini.

However, return values from Escape-Houldini come with unset utf8 flag. This can lead to unexpected double utf8 encoding, as it was for me in Template::Moustache.

Therefore I propose to set utf8 flag on all return values, see patch in 
https://github.com/yanick/Escape-Houdini/pull/6

**Comment by yanick** [comment]
Long merged in. Closing!
